"""Data contracts (Pydantic models) for all external sources and core entities."""

from huisChecker.contracts.entities import (
    Address,
    AreaMetricSnapshot,
    BagObject,
    ImportJob,
    ImportJobStatus,
    Municipality,
    Payment,
    PaymentStatus,
    Postcode4Area,
    Province,
    Report,
    ReportAccessLink,
    ReportFindingPayload,
    ReportModuleResult,
    ReportModuleStatus,
    ReportStatus,
    SourceDataset,
)
from huisChecker.contracts.identifiers import (
    BagObjectId,
    MunicipalityCode,
    NummeraanduidingId,
    Postcode,
    Postcode4,
    ProvinceCode,
    canonical_address_id,
    postcode4_of,
)
from huisChecker.contracts.metrics import (
    ComparisonMode,
    GeographyLevel,
    MetricDefinition,
    MetricRegistry,
    metric_registry,
)

__all__ = [
    "Address",
    "AreaMetricSnapshot",
    "BagObject",
    "BagObjectId",
    "ComparisonMode",
    "GeographyLevel",
    "ImportJob",
    "ImportJobStatus",
    "MetricDefinition",
    "MetricRegistry",
    "Municipality",
    "MunicipalityCode",
    "NummeraanduidingId",
    "Payment",
    "PaymentStatus",
    "Postcode",
    "Postcode4",
    "Postcode4Area",
    "Province",
    "ProvinceCode",
    "Report",
    "ReportAccessLink",
    "ReportFindingPayload",
    "ReportModuleResult",
    "ReportModuleStatus",
    "ReportStatus",
    "SourceDataset",
    "canonical_address_id",
    "metric_registry",
    "postcode4_of",
]
